### ISSUE TITLE
Mint Y Legacy darker control themes dont have big bigger button & rounded corners

### ISSUE THREAD

**Issue by viveksreedharan88** [linuxmint/mint-l-theme#3]
Hi. I certanily understand that the darker control theme is labeled as legacy. However in LM 20.3 it used to have rounded corners and buttons were big. Now after LM 21, it is restored to small and non-curvy edges. Please do something. Either  1) bring a seperate set of darker control themes with rounded corners, or 2) update the legacy ones. I believe option 1 would be best. 
![Mint Y Legacy](https://user-images.githubusercontent.com/76948666/184539138-bf6c9c11-e7fd-49ac-9b6b-513bb154bb11.png)

**Comment by JosephMcc** [comment]
Moved this issue to where it belongs. I don't know what the future holds for these legacy themes but I highly doubt you'll be seeing things like additional window borders and such being added.

**Comment by viveksreedharan88** [comment]
@JosephMcc Its ok if legacy themes are knocked off. But the key requirement is the darker ones in the control themes. Right now the only ones with big buttons and rounded corners is either light (fully light) or dark (fully dark). But the darker ones offer a combination of both, which is really good! If a new set of darker control themes are introduced, there would be no need for legacy ones.

**Comment by JosephMcc** [comment]
There is no intention on bringing back a darker version of the main theme. They were removed for a reason, which was talked about a good bit on the Mint blog. So don't expect any new darker version of mint-themes to be coming.

**Comment by viveksreedharan88** [comment]
Well, if you say so! Ok! I leave it upto u guys! However it`ll be great if user has a freedom to select what they want! Have a great day!

**Comment by JosephMcc** [comment]
You do have the freedom to choose. In the end we can only maintain so many things and keep them working correctly. But when comes to gtk themes there are tons of them out there done by the community and available to use.

**Comment by viveksreedharan88** [comment]
Joe, i am not sure if you have really understood what I have written. Darker themes with rounded corners. This is not something we can find in other gtk themes. When you guys can modify the light and dark themes with round corners, why skip only the darker ones? If there was an option to get elsewhere, i wouldn't even spend time in raising it here. Rather than telling me it can't be done, i belive it'll be much better that you check internally first. What i am asking is a very minor modification.

**Comment by clefebvre** [comment]
This is the theme as it was in 20.2.

**Comment by viveksreedharan88** [comment]
Hi Clem,

Thanks for the response. The darker themes even now has the design same as
legacy ones. It does not have rounded corners. This is true even today and
such themes are marked as legacy even today.

The new light and dark themes after LM  20.2 are little larger and the
right corner button of the window has rounded corners. But this is
available only for light and dark themes.

It will be very much appreciated if the same can be replicated to darker
themes.

I would leave it to you. You may decide what you find it fit.
