### ISSUE TITLE
Mint Y Legacy Dark Blue/Red doesn't looks like what Linux Mint 20.3/21 had

### ISSUE THREAD

**Issue by KarmyDev** [linuxmint/mint-l-theme#5]
Linux Mint 21.1 with their "legacy" themes doesn't look at all like what was in Linux Mint 20.3/21
![image](https://user-images.githubusercontent.com/32240709/209146567-a38147a6-6541-440f-8514-8d11dcc74a60.png)

Below is how Linux Mint 20.3/21 looked like:
![image](https://user-images.githubusercontent.com/32240709/209147621-6ca3f56a-faaa-40d4-bf6f-fe83c8fac496.png)

Hate having to downgrade Linux Mint just to have normal theme

**Comment by clefebvre** [comment]
It's the 20.2 look: https://github.com/linuxmint/mint-l-theme/issues/8.
