### ISSUE TITLE
Mint-Y-Legacy-Dark: text color in gnome-calendar events makes them unreadable 

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint-l-theme#9]
LM 21.1

![lm21 1](https://github.com/linuxmint/mint-l-icons/assets/68134588/a893b225-144c-47d5-ad7d-355af398efc0)

Similar to #[331] (https://github.com/linuxmint/mint-themes/issues/331)

**Comment by JosephMcc** [comment]
That same fix probably just needs to be ported. It probably came after the split of the two themes.

**Comment by haggen88** [comment]
This problem is also present in LM21.2 beta.

**Comment by haggen88** [comment]
Fixed for [ 21.2](https://github.com/linuxmint/mint-l-theme/commit/f3f389a144e0592a532de950e1976d9f88ae9b5a) in 1.9.5
